### ISSUE TITLE
ESL support

### ISSUE THREAD

**Issue by vensko** [matortheeternal/smash#164]
Mator Smash shows ESL files in the plugin selection window, yet ESL files are not shown in the main window afterwards. Would be nice to be able to smash ESL files as well, especially with possibility to enable a lot of them, what increases the chance of mod conflicts.

**Comment by matortheeternal** [comment]
ESLs will be removed from the plugin selection window in the next release.

Note that, because ESLs are loaded into load order slot 0xFE, they _cannot be patched_.

**Comment by mlandstreet** [comment]
Colin,

 

I have built what appear to be working patches for .esl files in FO4Edit. It seems that though they have the FE:xx indexing the game loads in this order:

 

Official .esm files

Mod .esm files

Official .esl files

Mod .esl files

.esp files.

 

Please correct me if I am wrong. As I recall I was reading a forum post by Zilav that was explain this and that was what made me experiment with it. 

 

I know it seems completely wrong but it seems Bethesda is ignoring the numeric values of the .esl plugins in the sorting and loading of plugins.

 

Thanks,

Mason

**Comment by matortheeternal** [comment]
Hi @mlandstreet, you may be correct.  I'll look into supporting loading of ESL files once I have updated the xEdit codebase used by smash so ESL files can be loaded properly.

**Comment by vensko** [comment]
I just checked too, and yes, ESLs are perfectly patchable with ESPs, and they don't event have to be their masters.

Here is the corresponding issue for xEdit https://github.com/TES5Edit/TES5Edit/issues/455

**Comment by vensko** [comment]
As a workaround, we can use ESL-flagged ESPs https://github.com/Modorganizer2/modorganizer/issues/207#issuecomment-359518047

MS loads them fine, but building patches stops with the "Maximum load order reached!" message. Is this an artificial limitation? Can it be removed?

**Comment by PhoenixTheSage** [comment]
Well, xEdit really should be updated to recognize ESPs that currently have the ESL flag as FE merge-types, like LOOT does...it's kinda late to the party. They are massively beneficial and starting to be more widely used.

**Comment by EnmaPlays** [comment]
xEdit has partial support.
Related:
https://github.com/TES5Edit/TES5Edit/issues/455

**Comment by matortheeternal** [comment]
> Well, xEdit really should be updated to recognize ESPs that currently have the ESL flag as FE merge-types, like LOOT does...it's kinda late to the party. They are massively beneficial and starting to be used more widely.

@PhoenixTheSage What xEdit does is *a lot* more in-depth compared to what LOOT does, so updating it to load ESLs in the FE slot is a bit more complicated.  The entire xEdit framework has been built on the idea of the 255-plugin load order - it is absolutely not trivial to make ESLs load into the FE slot and keep the rest of xEdit's features intact.

**Comment by PhoenixTheSage** [comment]
I know :) I'm not comparing the back-end. Just the front-end. It doesn't change the fact it's going to have to be done. The community will sorta outrun the tool for a while until it does.

**Comment by matortheeternal** [comment]
> People are already converting dozens, to hundreds of mods, to ESP-FE and ESL.

Maybe they shouldn't.  Maybe they should just merge plugins using stay below the 255-plugin limit and treat existing ESLs like ESPs.  Suggesting that all of the tools have to change to meet a new workflow when an existing workflow is sufficient is a bit silly.

**Comment by ChaoticTabris** [comment]
Well... There are advantages to using ESPs flagged as ESLs. It's easier to update and there is less potential for incompatibilities and bugs. Not being entitled here and demanding this to be implemented as i'm perfectly fine using ESPs flagged as ESLs and patching them manually using SSEdit (Not activating more than 255 at a time) instead of merging hundreds of ESP files.

I guess this is a problem that will only really affect extreme users like me that tend to be WAAAAAY over the plugin limit so it's probably not a priority issue.

**Comment by matortheeternal** [comment]
> I guess this is a problem that will only really affect extreme users like me that tend to be WAAAAAY over the plugin limit so it's probably not a priority issue.

There are many users who have managed to merge hundreds, if not thousands of plugin files successfully.  I understand that using ESLs may seem easier, but the downsides greatly outweigh the benefits, in my eyes.  You won't be able to use pretty much every tool I make, and any tools which are built on libraries I develop or build off of the xEdit framework.  This includes:

- UPF Patchers
- MXPF Patchers
- DynDOLOD
- xEdit/zEdit with full load order
- Mator Smash
- others?

That's a lot to miss out on for "muh ESLs".  But hey, you guys can do what you want.  Just keep your ESL shenanigans away from me.  :stuck_out_tongue_winking_eye:

**Comment by ChaoticTabris** [comment]
If you say so i guess i'll give merging another try. Maybe i'm being too cautious and could be doing bigger merges instead of several smaller ones.

**Comment by mtjohnson47** [comment]
Any updates on ESL?

**Comment by matortheeternal** [comment]
ESL support is no longer planned due to the 255 master limitation on plugin files.

**Comment by matortheeternal** [comment]
> Why not circumvent that by splitting the smash into multiple files depending on the master count?

Because in order for that to be effective, the multiple patches cannot conflict - so you need to find groups of plugins where the groups do not conflict with each other to patch.

Ultimately what I'm going to do is make an option which users can enable to "only add required masters" while patching.  When users enable this, smash will add masters as necessary while it's patching, which will make it run ~50% slower.  This will most likely end up happening in zSmash, the zEdit application mode I'm planning on making to replace Smash.

**Comment by blureshadow** [comment]
Thank you for the reply, I assume there is no ETA on the release of zSmash?

**Comment by matortheeternal** [comment]
I haven't even started developing it, but I am thinking about it on a regular basis and I'm excited to make it.  I tend to be very optimistic with estimates on projects, so I'll just provide some facts and you can draw what conclusion you will:

- I started on zMerge 11/21/2017.  The first alpha was made available 9/11/2018.  The first public release was made available 10/29/2018.
- Development of zMerge was intermittent during this time, and other parts of zEdit were being actively developed simultaneously.  A lot of internal APIs were reworked for zMerge.
- zSmash will be the third "additional" application mode added to zEdit, so it should be easier than previous application modes to develop.
- zMerge requires a lot of logic which zSmash doesn't because it needs to handle asset files, but zSmash requires a bit more GUI work.
- Mator Smash was developed faster than Merge Plugins.  Development started October 18, 2015, and the first alpha release was made available November 7, 2015 (a mere 3 weeks later).

**Comment by BLACKBERREST3** [comment]
2020 progress update?

**Comment by matortheeternal** [comment]
@BLACKBERREST3 Mator Smash is no longer being developed, a replacement zSmash is being developed as an application mode for zEdit.  I haven't been coding very actively on my projects for awhile, but started to get back into the swing of things over the last month.

**Comment by BLACKBERREST3** [comment]
Happy to see you coding again, I love your work. I forget why I posted in a closed topic, tbh, I wasn't expecting a response now that I'm remembering XD. I was originally looking for recent posts you had made and couldn't find any at that time. I'm fairly new to modding and can't wait to get into patching/mod creation and I know I'm going to be using your tools to do so. Someday I'll be able to play skyrim with my 400 or so mods...someday. Until then I'll be reading up a storm. Thank you for responding btw, it's nice to know there are still awesome people active in the modding community.
