### ISSUE TITLE
Some leveled lists not forwarding records.. tried various bash tags

### ISSUE THREAD

**Issue by AerowynX** [matortheeternal/smash#225]
tried smash.all, lev, relev and no matter what I can't get immersive weapons to forward its records.. wyre bash handles it fine.. any idea why it won't forward the records for IW? oddly it seems to forward the generic record but not the one specific to IW

https://imgur.com/LEvGgqx

**Comment by AerowynX** [comment]
well spoke to soon.. ran smash again and didn't change any tags this time and back to not forwarding the leveled lists again.. guess will just have to use wyre for leveled list and smash for everything else

**Comment by AerowynX** [comment]
looks like Smash.OverrideAll solves this so guess not really an issue

**Comment by AerowynX** [comment]
so still having issue with immersive weapons.. no matter what tags I use it won't forward the records.. even if I copy the records to another mod and try to use forceall or override or anything else it just won't forward them.. can't figure this out as wyre bash has no problem with IW

this is with using override all tag https://imgur.com/KCiHMNt

**Comment by matortheeternal** [comment]
You guys seem to be poorly informed about how smash decides to forward changes.

The problem you're having is because one of your plugins has `ImmersiveWeapons.esp` as a master, overrides leveled list records from it, and deletes the entries.  Smash sees this as an "informed deletion" - viz., the plugin KNOWS `ImmersiveWeapons.esp` exists, saw its leveled list entries, and then decided to remove them from the game.  Smash is simply following what your plugins are telling it to do.  Preserving leveled list entries when a plugin *knowingly removes them* would be buggy behavior.

The only way to make that plugin NOT delete the entries from `ImmersiveWeapons.esp` is to disable "preserve deletions" for the `Leveled List Items` array in the smash setting used on that plugin.
