### ISSUE TITLE
 Deletions of leveled lists entries added in non-masters are not preserved

### ISSUE THREAD

**Issue by MagielBruntink** [matortheeternal/smash#36]
For instance: Weapons & Armor Fixes Remade.esp adds a LItemEnchDwarvenSword at level 7 to LItemEnchWeaponSwordBlacksmith. MLU.esp removes the sword again. Smashed Patch will still have the sword in the same list, even if "preserve deletion" flags are turned on.

**Comment by matortheeternal** [comment]
Hmm.  Yes, I think I was aware of this, but it does need to be tackled.  Thanks!

**Comment by matortheeternal** [comment]
Hi @MagielBruntink,

I looked into the specific case you were interested in with the plugins:
* `Weapons & Armor Fixes_Remade.esp`
* `MLU.esp`

`MLU.esp` doesn't use `Weapons & Armor Fixes_Remade.esp` as a master, so how can smash recognize that MLU.esp is "deleting" those Leveled list entries?  Because MLU.esp isn't deleting them, it's just *not adding them*.  There's a strict difference between these two things.  Deletion implies knowledge of existence.  MLU.esp does not know that these other items exist in the Leveled List, so Smash will not remove them from the Leveled List just because MLU.esp doesn't have them.  That'd completely ruin the point.

What you want to do is treat the `Leveled List Entries` element as a single entity on MLU.esp.
